name: Link Check

on:
  push:
    paths: ["**/*.md"]
  pull_request:
    paths: ["**/*.md"]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: "--verbose --no-progress **/*.md"
